// ── PDF export using jsPDF ────────────────────────────────────────────────
import type { Complaint } from "./types";

export async function generatePDF(complaint: Complaint): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF();
  const margin = 20;
  let y = margin;
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - margin * 2;

  // Header
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 40, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("CIVIC COMPLAINT", margin, 26);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`ID: ${complaint.id}`, pageWidth - margin - 50, 20);
  doc.text(
    `Date: ${new Date(complaint.timestamp).toLocaleDateString("en-IN")}`,
    pageWidth - margin - 50,
    28
  );

  y = 55;
  doc.setTextColor(30, 30, 30);

  // To / Department
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("To:", margin, y);
  doc.setFont("helvetica", "normal");
  doc.text(complaint.department, margin + 12, y);
  y += 12;

  // Subject
  doc.setFont("helvetica", "bold");
  doc.text("Subject:", margin, y);
  doc.setFont("helvetica", "normal");
  const titleLines = doc.splitTextToSize(complaint.title, contentWidth - 25);
  doc.text(titleLines, margin + 25, y);
  y += titleLines.length * 6 + 10;

  // Severity & Type
  doc.setFont("helvetica", "bold");
  doc.text(`Issue Type: `, margin, y);
  doc.setFont("helvetica", "normal");
  doc.text(complaint.issue_type.replace(/_/g, " ").toUpperCase(), margin + 32, y);
  doc.setFont("helvetica", "bold");
  doc.text(`Severity: `, margin + 100, y);
  doc.setFont("helvetica", "normal");
  doc.text(complaint.severity.toUpperCase(), margin + 125, y);
  y += 12;

  // Location
  doc.setFont("helvetica", "bold");
  doc.text("Location:", margin, y);
  doc.setFont("helvetica", "normal");
  doc.text(complaint.location || "Not specified", margin + 28, y);
  y += 8;
  if (complaint.landmark) {
    doc.setFont("helvetica", "bold");
    doc.text("Landmark:", margin, y);
    doc.setFont("helvetica", "normal");
    doc.text(complaint.landmark, margin + 28, y);
    y += 8;
  }
  y += 8;

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Body
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  const bodyLines = doc.splitTextToSize(complaint.description, contentWidth);
  doc.text(bodyLines, margin, y);
  y += bodyLines.length * 6 + 16;

  // Footer
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text("Generated by Civic Complaint Copilot", margin, y);
  doc.text(`Complaint ID: ${complaint.id}`, pageWidth - margin - 55, y);

  doc.save(`complaint-${complaint.id}.pdf`);
}
